$ErrorActionPreference = "Stop"

Write-Host "Prometheus port-forward command:"
Write-Host "kubectl --context=fraud-mlops-p4 -n fraud-mlops port-forward service/prometheus-service 9090:9090"
Write-Host ""
Write-Host "Grafana port-forward command:"
Write-Host "kubectl --context=fraud-mlops-p4 -n fraud-mlops port-forward service/grafana-service 3000:3000"
Write-Host ""
Write-Host "Prometheus:"
Write-Host "http://127.0.0.1:9090"
Write-Host ""
Write-Host "Grafana:"
Write-Host "http://127.0.0.1:3000"
Write-Host ""
Write-Host "Grafana login:"
Write-Host "admin / admin"
